<?php
$connection = new MongoClient();
$db = $connection -> qandm;
$collection = $db -> suggestionData;


$userName = $_POST['userNameVal'];  

$suggestionArray = array(
	"The Shawshank Redemption ",
	"The Godfather ",
	"The Godfather: Part II ",
	"Pulp Fiction ",
	"The Good, the Bad and the Ugly ",
	"12 Angry Men",
	"The Dark Knight ",
	"Schindler's List ",
	"The Lord of the Rings: The Return of the King",
	"Fight Club ",
	"Star Wars: Episode V - The Empire Strikes Back",
	"The Lord of the Rings: The Fellowship of the Ring",
	"One Flew Over the Cuckoo's Nest ",
	"Inception ",
	"Goodfellas ",
	"Star Wars ",
	"Seven Samurai ",
	"Forrest Gump ",
	"The Matrix ",
	"The Lord of the Rings: The Two Towers ",
	"City of God ",
	"Se7en ",
	"The Silence of the Lambs",
	"Once Upon a Time in the West ",
	"Casablanca ",
	"The Usual Suspects ",
	"Raiders of the Lost Ark ",
	"Rear Window ",
	"It's a Wonderful Life ",
	"Psycho ",
	"Leon: The Professional ",
	"Sunset Blvd. ",
	"American History X ",
	"Memento ",
	"Apocalypse Now ",
	"Terminator : Judgment Day ",
	"Saving Private Ryan ",
	"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb ",
	"City Lights ",
	"Alien ",
	"Spirited Away ",
	"North by Northwest ",
	"Modern Times ",
	"Django Unchained ",
	"Citizen Kane ",
	"Back to the Future ",
	"The Shining ",
	"The Pianist ",
	"The Dark Knight Rises ",
	"Life Is Beautiful ",
	"The Departed ",
	"M ",
	"Vertigo ",
	"Paths of Glory ",
	"American Beauty ",
	"Taxi Driver ",
	"Double Indemnity ",
	"Aliens ",
	"Toy Story 3",
	"WALL·E ",
	"The Lives of Others ",
	"The Intouchables ",
	"The Green Mile ",
	"Gladiator ",
	"A Clockwork Orange ",
	"The Great Dictator ",
	"Amelie ",
	"The Prestige ",
	"Lawrence of Arabia ",
	"To Kill a Mockingbird ",
	"Reservoir Dogs ",
	"Das Boot ",
	"Cinema Paradiso ",
	"The Third Man ",
	"Requiem for a Dream ",
	"The Lion King ",
	"The Treasure of the Sierra Madre ",
	"Eternal Sunshine of the Spotless Mind ",
	"Once Upon a Time in America ",
	"Star Wars: Episode VI - Return of the Jedi ",
	"Full Metal Jacket ",
	"L.A. Confidential ",
	"Braveheart ",
	"Chinatown ",
	"Oldboy ",
	"Singin' in the Rain ",
	"Monty Python and the Holy Grail ",
	"Some Like It Hot ",
	"Bicycle Thieves ",
	"Metropolis ",
	"Amadeus ",
	"Rashomon ",
	"Princess Mononoke ",
	"2001: A Space Odyssey ",
	"All About Eve ",
	"The Sting ",
	"Unforgiven ",
	"Indiana Jones and the Last Crusade ",
	"The Apartment ",
	"Raging Bull ",
	"The Bridge on the River Kwai ",
	"Witness for the Prosecution ",
	"Grave of the Fireflies ",
	"Die Hard ",
	"Batman Begins ",
	"A Separation ",
	"Yojimbo ",
	"Inglourious Basterds ",
	"Snatch. ",
	"For a Few Dollars More ",
	"The Great Escape ",
	"Pan's Labyrinth ",
	"Downfall ",
	"Mr. Smith Goes to Washington ",
	"Up ",
	"Toy Story 1",
	"On the Waterfront ",
	"The Elephant Man ",
	"The Seventh Seal ",
	"The General ",
	"Heat ",
	"The Maltese Falcon ",
	"Blade Runner ",
	"The Kid ",
	"Rebecca ",
	"Gran Torino ",
	"Wild Strawberries ",
	"Scarface ",
	"Fargo ",
	"Ran ",
	"The Big Lebowski ",
	"Touch of Evil ",
	"The Deer Hunter ",
	"Cool Hand Luke ",
	"The Gold Rush ",
	"Lock, Stock and Two Smoking Barrels ",
	"No Country for Old Men ",
	"It Happened One Night ",
	"Sin City ",
	"Strangers on a Train ",
	"Casino ",
	"The Sixth Sense ",
	"Jaws ",
	"Platoon ",
	"The Thing ",
	"Butch Cassidy and the Sundance Kid ",
	"Trainspotting ",
	"The Wizard of Oz ",
	"High Noon ",
	"The Avengers ",
	"Good Will Hunting ",
	"Hotel Rwanda ",
	"Kill Bill: Vol.  ",
	"Warrior ",
	"The Secret in Their Eyes ",
	"Annie Hall ",
	"Gone with the Wind ",
	"The Grapes of Wrath ",
	"My Neighbor Totoro ",
	"Notorious ",
	"V for Vendetta ",
	"Into the Wild ",
	"Finding Nemo ",
	"Life of Brian ",
	"Dial M for Murder ",
	"How to Train Your Dragon ",
	"The King's Speech ",
	"There Will Be Blood ",
	"The Big Sleep ",
	"The Night of the Hunter ",
	"The Terminator ",
	"Ben-Hur ",
	"Network ",
	"Million Dollar Baby ",
	"Stand by Me ",
	"Groundhog Day ",
	"The Best Years of Our Lives ",
	"Donnie Darko ",
	"Twelve Monkeys ",
	"Dog Day Afternoon ",
	"Mary and Max ",
	"The 400 Blows ",
	"Amores Perros ",
	"Black Swan ",
	"The Bourne Ultimatum ",
	"Persona ",
	"Gandhi ",
	"Howl's Moving Castle ",
	"The Killing ",
	"The Graduate ",
	"A Beautiful Mind ",
	"The Princess Bride ",
	"8 1/2 ",
	"Life of Pi ",
	"The Hobbit: An Unexpected Journey ",
	"Who's Afraid of Virginia Woolf? ",
	"The Hustler ",
	"La Strada ",
	"Slumdog Millionaire ",
	"Rocky ",
	"Anatomy of a Murder ",
	"The Manchurian Candidate ",
	"The Exorcist ",
	"The Wild Bunch ",
	"The Man Who Shot Liberty Valance ",
	"Rope ",
	"Barry Lyndon ",
	"Stalag  ",
	"The Artist",
	"Sleuth ",
	"Stalker ",
	"In the Name of the Father ",
	"Infernal Affairs ",
	"Roman Holiday ",
	"The Truman Show ",
	"Memories of Murder ",
	"Pirates of the Caribbean: The Curse of the Black Pearl",
	"Monsters, Inc. ",
	"District 9",
	"A Fistful of Dollars ",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Ip Man ",
	"The Diving Bell and the Butterfly ",
	"Ratatouille ",
	"Star Trek ",
	"A Streetcar Named Desire ",
	"Jurassic Park ",
	"La Haine ",
	"Shutter Island ",
	"3 Idiots ",
	"All Quiet on the Western Front ",
	"Incendies ",
	"Beauty and the Beast ",
	"Rain Man ",
	"Rosemary's Baby ",
	"Like Stars on Earth ",
	"Nausicaä of the Valley of the Wind ",
	"Harvey ",
	"Mystic River ",
	"Papillon ",
	"Manhattan ",
	"The Perks of Being a Wallflower ",
	"Nosferatu ",
	"Spring, Summer, Fall, Winter... and Spring ",
	"The Help ",
	"Three Colors: Red ",
	"The Untouchables ",
	"The Wrestler ",
	"The Celebration ",
	"Battleship Potemkin ");

$strength = rand(1, 3);
$strength2 = rand(1, 3);

$suggestionPicker = rand(0, 249);
$suggestionPicker2 = rand(0, 249);

$suggestion = $suggestionArray[$suggestionPicker];
$suggestion2 = $suggestionArray[$suggestionPicker2];

$json = array("Username" => $userName, "Suggestion" => $suggestion, "Strength" => $strength );
$json2 = array("Username" => $userName, "Suggestion" => $suggestion2, "Strength" => $strength2 );

$collection -> insert($json);
$collection -> insert($json2);

		echo '<div style="background-color:rgba(';
		if($strength == 3){ echo "217, 201, 0, 255"; }
		else if($strength == 2){ echo "193, 98, 33, 255"; }	
		else if($strength == 1){ echo "199, 30, 104, 255"; }
		echo ');"><center>';
		echo $suggestion;
		echo '</center></div>';
		
		echo '<div style="background-color:rgba(';
		if($strength2 == 3){ echo "217, 201, 0, 255"; }
		else if($strength2 == 2){ echo "193, 98, 33, 255"; }	
		else if($strength2 == 1){ echo "199, 30, 104, 255"; }
		echo ');"><center>';
		echo $suggestion2;
		echo '</center></div>';
		
?>  